# Generated by Django 5.1.4 on 2025-06-19 17:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active')),
                ('business_name', models.CharField(help_text='Official business name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly store name', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Vendor description')),
                ('logo', models.ImageField(blank=True, help_text='Vendor logo', null=True, upload_to='vendors/logos/')),
                ('banner', models.ImageField(blank=True, help_text='Store banner image', null=True, upload_to='vendors/banners/')),
                ('email', models.EmailField(help_text='Business email address', max_length=254)),
                ('phone', models.CharField(help_text='Business phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True, help_text='Business website URL')),
                ('address_line_1', models.CharField(help_text='Street address', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, etc.', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal/ZIP code', max_length=20)),
                ('country', models.CharField(default='Nigeria', help_text='Country', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
                ('registration_number', models.CharField(blank=True, help_text='Business registration number', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether vendor is verified')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether vendor is approved to sell')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('user_id', models.UUIDField(help_text='Supabase user ID', primary_key=True, serialize=False)),
                ('business_name', models.CharField(help_text='Official business name', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of business name', max_length=100, unique=True)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp contact number', max_length=20)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name for payments', max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=20)),
                ('account_name', models.CharField(blank=True, help_text='Account holder name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether vendor profile is active')),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active')),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=100)),
                ('account_name', models.CharField(help_text='Account holder name', max_length=200)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=50)),
                ('routing_number', models.CharField(blank=True, help_text='Bank routing number (if applicable)', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary account for payments')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether account is verified')),
                ('vendor', models.ForeignKey(help_text='Vendor this account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Bank Account',
                'verbose_name_plural': 'Vendor Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='VendorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record should be treated as active')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount', max_digits=10)),
                ('processing_time', models.PositiveIntegerField(default=1, help_text='Order processing time in days')),
                ('return_policy', models.TextField(blank=True, help_text='Return policy text')),
                ('vendor', models.OneToOneField(help_text='Vendor these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Settings',
                'verbose_name_plural': 'Vendor Settings',
            },
        ),
    ]
