# Generated by Django 5.1.4 on 2025-06-19 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique collection identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Collection name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Collection description')),
                ('is_public', models.BooleanField(default=True, help_text='Whether collection is publicly visible')),
                ('products', models.ManyToManyField(blank=True, help_text='Products in this collection', related_name='collections', to='products.product')),
                ('vendor', models.ForeignKey(help_text='Vendor who owns this collection', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', '-created_at'], name='products_co_vendor__32ed54_idx'), models.Index(fields=['is_public', '-created_at'], name='products_co_is_publ_51a048_idx'), models.Index(fields=['name'], name='products_co_name_50d614_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'name'), name='unique_collection_name_per_vendor')],
            },
        ),
    ]
