// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pajpblpigrkpvmzoqabz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhanBibHBpZ3JrcHZtem9xYWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTgwODksImV4cCI6MjA2NTY3NDA4OX0.K4J_JANEtAdwLwYne2uGRoEbY5HnC-CxtK9aUevG3Ds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);